---
title: "LAB9"
author: "Caroline Martin"
date: "10/26/2020"
output: html_document
---

```{r}
library(stringr)
library(tidyverse)
```

```{r}
x <- c("apple", "banana", "pear")
str_view(x, "an")
```

```{r}
str_view(x, ".a.")
```

```{r}
# To create the regular expression, we need \\
dot <- "\\."

# But the expression itself only contains one:
writeLines(dot)
```

```{r}
# This tells R to look for an explicit .
x <- c("abc", "a.c", "bef")
str_view(x, "a\\.c")
```

```{r}
x <- "a\\b"
writeLines(x)
```

```{r}
str_view(x, "\\\\")
```

#14.3.1.1 Exercises
```{r}
# 1. "\" does not match \ because in order to match one \, there needs to be two
# "\\" doesn't match \ because there needs to be a . included
# "\\\" doesn't match \ because it's an odd number and also doesn't include a . 

# 2. to match seq. "'\" I would match it with "'\\"
# 3. 
```

#14.3.2 Anchors
```{r}
x <- c("apple", "banana", "pear")
str_view(x, "^a")
```

```{r}
str_view(x, "a$")
```

```{r}
x <- c("apple pie", "apple", "apple cake")
str_view(x, "apple")
```

```{r}
str_view(x, "^apple$")
```

```{r}
#How would you match the literal string "$^$"?
x <- c("$$$", "$^$", "^$$")
str_view(x, "$^$")
```

```{r}
#Given the corpus of common words in stringr::words, create regular expressions that find all words that:

d <- c("yellow", "anticlimax", "sit")
```

```{r}
#Start with “y”.
str_view(d, "^y")
```

```{r}
#End with “x”
str_view(d, "x$")
```

```{r}
#Are exactly three letters long. (Don’t cheat by using str_length()!)
str_view(d, "^...$")
```

```{r}
#Have seven letters or more.
str_view(d, "^.......")
```

#14.3.3 Character classes and alternatives
```{r}
# Look for a literal character that normally has special meaning in a regex
x <- c("abc", "a.c", "a*c", "a c")
str_view(x, "a[.]c", match = TRUE)
```

```{r}
str_view(x, ".[*]c")
```

```{r}
str_view(x, "a[ ]")
```

```{r}
x <- c("grey", "gray")
str_view(x, "gr(e|a)y")
```

#14.3.3.1 Exercises
```{r}
#Create regular expressions to find all words that:
str_subset(stringr::words, "^[aeiou]")
```

```{r}
#Start with a vowel.
str_subset(stringr::words, "^[aeiou]")
```

```{r}
#That only contain consonants. (Hint: thinking about matching “not”-vowels.)
str_subset(stringr::words, "[aeiou]", negate=TRUE)
```

```{r}
#End with ed, but not with eed.
str_subset(stringr::words, "[^e]ed$")
```
```{r}
#End with ing or ise.
str_subset(stringr::words, "i(ng|se)$")
```

#14.3.4 Repetition
```{r}
x <- "1888 is the longest year in Roman numerals: MDCCCLXXXVIII"
str_view(x, "CC?")
```

```{r}
str_view(x, "CC+")
```

```{r}
str_view(x, 'C[LX]+')
```

```{r}
str_view(x, "C{2}")
```

```{r}
str_view(x, "C{2,}")
```

```{r}
str_view(x, 'C{2,3}?')
```

```{r}
str_view(x, 'C[LX]+?')
```

#14.3.5
```{r}
str_view(fruit, "(..)\\1", match = TRUE)
```

#14.3.5 Exercises
```{r}
str_view(fruit, "(.)(.)\\2\\1", match = TRUE)
#
```
#14.4.1
```{r}
f <- c("apple", "banana", "pear")
str_detect(f, "e")
```

```{r}
sum(str_detect(words, "^t"))
```

```{r}
mean(str_detect(words, "[aeiou]$"))
```

```{r}
# Find all words containing at least one vowel, and negate
no_vowels_1 <- !str_detect(words, "[aeiou]")
```

```{r}
no_vowels_2 <- str_detect(words, "^[^aeiou]+$")
identical(no_vowels_1, no_vowels_2)
```

```{r}
words[str_detect(words, "x$")]
```

```{r}
str_subset(words, "x$")
```

```{r}
df <- tibble(
  word = words, 
  i = seq_along(word)
)
df %>% 
  filter(str_detect(word, "x$"))
```

```{r}
f <- c("apple", "banana", "pear")
str_count(f, "a")
```

```{r}
# On average, how many vowels per word?
mean(str_count(words, "[aeiou]"))
```

```{r}
df %>% 
  mutate(
    vowels = str_count(word, "[aeiou]"),
    consonants = str_count(word, "[^aeiou]")
  )
```

```{r}
str_count("abababa", "aba")
```

```{r}
str_view_all("abababa", "aba")
```

#14.4.1 Exercises
```{r}
words[str_detect(words, "^x|x$")]
```

```{r}
start_with_x <- str_detect(words, "^x")
end_with_x <- str_detect(words, "x$")
words[start_with_x | end_with_x]
```

```{r}
str_subset(words, "^[aeiou].*[^aeiou]$") %>% head()
```

```{r}
start_vowel <- str_detect(words, "^[aeiou]")
end_consonant <- str_detect(words, "[^aeiou]$")
words[start_vowel & end_consonant] %>% head()
```

##14.4.2
```{r}
length(sentences)
```

```{r}
head(sentences)
```

```{r}
colours <- c("red", "orange", "yellow", "green", "blue", "purple")
colour_match <- str_c(colours, collapse = "|")
colour_match
```

```{r}
has_colour <- str_subset(sentences, colour_match)
matches <- str_extract(has_colour, colour_match)
head(matches)
```

```{r}
has_colour
```

```{r}
more <- sentences[str_count(sentences, colour_match) > 1]
str_view_all(more, colour_match)
```

```{r}
str_extract(more, colour_match)
```

```{r}
str_extract_all(more, colour_match)
```

```{r}
str_extract_all(more, colour_match, simplify = TRUE)
```

```{r}
x <- c("a", "a b", "a b c")
str_extract_all(x, "[a-z]", simplify = TRUE)
```

##14.4.2 Exercises 
```{r}
#In the previous example, you might have noticed that the regular expression matched “flickered”, which is not a colour. Modify the regex to fix the problem.
colours <- c("red", "orange", "yellow", "green", "blue", "purple")
colour_match <- str_c(colours, collapse = "|")
colour_match2 <- str_c("\\b(", str_c(colours, collapse = "|"), ")\\b")
more2 <- sentences[str_count(sentences, colour_match) > 1]
str_view_all(more2, colour_match2, match = TRUE)
```

##14.4.3
```{r}
noun <- "(a|the) ([^ ]+)"

has_noun <- sentences %>%
  str_subset(noun) %>%
  head(10)
has_noun %>% 
  str_extract(noun)
```

```{r}
has_noun %>% 
  str_match(noun)
```

```{r}
tibble(sentence = sentences) %>% 
  tidyr::extract(
    sentence, c("article", "noun"), "(a|the) ([^ ]+)", 
    remove = FALSE
  )
```

##14.4.3 Exercises
```{r}
#Find all words that come after a “number” like “one”, “two”, “three” etc. Pull out both the number and the word.

numword <- "\\b(one|two|three|four|five|six|seven|eight|nine|ten) +(\\w+)"
sentences[str_detect(sentences, numword)] %>%
  str_extract(numword)
```

##14.4.4
```{r}
x <- c("apple", "pear", "banana")
str_replace(x, "[aeiou]", "-")
```

```{r}
str_replace_all(x, "[aeiou]", "-")
```

```{r}
x <- c("1 house", "2 cars", "3 people")
str_replace_all(x, c("1" = "one", "2" = "two", "3" = "three"))
```

```{r}
sentences %>% 
  str_replace("([^ ]+) ([^ ]+) ([^ ]+)", "\\1 \\3 \\2") %>% 
  head(5)
```

##14.4.4 Exercises
```{r}
#Replace all forward slashes in a string with backslashes.

str_replace_all("past/present/future", "/", "\\\\")

```

##14.4.5
```{r}
sentences %>%
  head(5) %>% 
  str_split(" ")
```

```{r}
"a|b|c|d" %>% 
  str_split("\\|") %>% 
  .[[1]]
```

```{r}
fields <- c("Name: Hadley", "Country: NZ", "Age: 35")
fields %>% str_split(": ", n = 2, simplify = TRUE)
```
```{r}
x <- "This is a sentence.  This is another sentence."
str_view_all(x, boundary("word"))
```

```{r}
str_split(x, " ")[[1]]
```

```{r}
str_split(x, boundary("word"))[[1]]
```

##14.4.5 Exercises
```{r}
#Split up a string like “apples, pears, and bananas” into individual components.

x <- c("apples, pears, and bananas")
str_split(x, ", +(and +)?")[[1]]
```